services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: oceans
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
